### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by fighterzg6** [marcelkordek/homebridge-harman-kardon-avr#1]
Hallo,

Wie lade ich das Plugin herunter? Bräuchte es dringend

**Comment by marcelkordek** [comment]
Hallo fighterzg6,

probiere es mal mit:
`cd $(npm root -g) && sudo git clone https://github.com/marcelkordek/homebridge-harman-kardon-avr.git && cd homebridge-harman-kardon-avr && sudo npm install`

Die normale installation mit:
`sudo npm install -g https://github.com/marcelkordek/homebridge-harman-kardon-avr`

funktioniert bei mir zurzeit leider auch nicht.

Gruß
Marcel

**Comment by marcelkordek** [comment]
Habe gerade unter NODE v10.15.0 und NPM 6.4.1 getestet.

Die installation mit: 
`sudo npm install -g https://github.com/marcelkordek/homebridge-harman-kardon-avr`

funktioniert da einwandfrei. Scheint ein NPM Problem gewesen zu sein.
Welche Version benutzt du?

**Comment by fighterzg6** [comment]
Hat super geklappt, danke

**Comment by fighterzg6** [comment]
Jetzt startet nur die homebridge nicht mehr, sagt mir ein Plugin wäre nicht installiert??

**Comment by marcelkordek** [comment]
Ok, prima.
In der homebridge config muss folgendes unter accessories hinzugefügt werden:

{
        "accessory": "Harman Kardon AVR",
        "name": "AVR",
        "description": "Harman Kardon AVR",
        "manufacturer": "Harman Kardon",
        "model_name": "AVR 161",
        "ip": "xx.x.x.xx",
        "port": "10025"
}

Was sagt denn homebridge genau beim starten?

**Comment by fighterzg6** [comment]
/usr/local/lib/node_modules/homebridge/lib/api.js 
throw new Error("The requested platform '" + name + "' was not registered by any plugin.");

**Comment by fighterzg6** [comment]
Scheint etwas mit der Config zu tun haben. Wenn ich den Eintrag aus der config lösche fährt die Bridge wieder hoch

**Comment by marcelkordek** [comment]
Hi,

probiere es bitte mal mit folgender config:

{
            "accessory": "harman-kardon-avr",
            "name": "Harman Kardon AVR",
            "description": "Harman Kardon AVR",
            "manufacturer": "Harman Kardon",
            "model_name": "AVR 161",
            "ip": "xxx.xxx.xxx.xxx",
            "port": "10025"
        }

**Comment by fighterzg6** [comment]
Super, jetzt klappt es.

Ich habe den avr 171, kann man da noch einzelne Befehle hinzufügen oder so, bräuchte noch TV Eingang usw.

**Comment by jhalscheidt** [comment]
Welche Befehle kann ich in HomeKit allgemein absetzen zum AVR? Habe momentan in Homekit nur 2 Schalter angezeigt. AVR AUS/EIN und SAT/STB AUS/EIN.

**Comment by marcelkordek** [comment]
Sorry für die späte Antwort. Es ist eine TV Steuerung geplant. Diese lässt sich allerdings aktuell noch nicht gut umsetzen, da der AVR leider keinen status zurückgibt.
Geplant sind folgende Möglichkeiten:

An/Aus
Lauter/Leiser
Eingänge wechseln

Gruß Marcel

**Comment by jhalscheidt** [comment]
Hallo Marcel, 

Leider bin ich nicht der gute Programmierer. 
Was ich aber öfter nutze ist die Steuerung von lauter und leiser über Spotify da der AVR ja Spotify Connect unterstützt. Das funktioniert eigentlich recht gut. 
Vielleicht hilft das ja wenn du per wireshark schaust was die Spotify App schickt bzw. empfängt. 

Gruß, Jörn 

Am 23.09.2019 um 23:00 schrieb Marcel <notifications@github.com>:

**Comment by fighterzg6** [comment]
hallo, gibt es schon Neuigkeiten ?? bin sehr interessiert!

**Comment by marcelkordek** [comment]
Bin gerade noch am testen. Das neue Plugin ist in kürze Funktionsfähig.

Gruß,
Marcel

**Comment by fighterzg6** [comment]
hallo, habe jetzt die version 2.0 installiert aber leider bringt er mir einen Fehler das node 9.9.0  nicht kompatibel sei? bridge startet auch nicht durch.

**Comment by marcelkordek** [comment]
Der Start Fehler ist behoben. Der Rest wird noch getestet und angepasst.

**Comment by fighterzg6** [comment]
super , funktioniert.!!! danke dafür! 
wie stelle ich die Eingänge richtig ein?? wenn ich in HomeKit tv wähle stellt er auf STB usw.
habe einen AVR 171

**Comment by fighterzg6** [comment]
ok zu früh gefreut , Homebridge stürzt immer ab. ich warte mal besser bis alles fertig ist

**Comment by marcelkordek** [comment]
Probiere es mal mit dem neusten update:

`sudo npm install -g @marcelkordek/homebridge-harman-kardon-avr`

**Comment by fighterzg6** [comment]
wenn ich es so installiere findet er das plugin nicht

**Comment by marcelkordek** [comment]
ok, dann bitte wieder direkt installieren. Neue version kann ich erst morgen bei NPM hochladen

**Comment by fighterzg6** [comment]
welcher link war das? komm langsam durcheinander

**Comment by marcelkordek** [comment]
cd $(npm root -g) && sudo git clone https://github.com/marcelkordek/homebridge-harman-kardon-avr.git && cd homebridge-harman-kardon-avr && sudo npm install

**Comment by fighterzg6** [comment]
npm install -g https://github.com/marcelkordek/homebridge-harman-kardon-avr
mit dem ging es und die Homebridge stürzt auch nicht ab!
bin gespannt wie es weiter geht

**Comment by fighterzg6** [comment]
also solange ich nichts auswähle läuft alles. wenn ich den avi ein oder ausschalte bzw den kanal Wechsel stürzt die bridge ab.

**Comment by marcelkordek** [comment]
Gibt dir Homebridge eine Fehlermeldung beim Absturz?

Bei mir läuft das ganze relativ zuverlässig (AVR 161). Allerdings gibt es ein paar Limitierungen da die Receiver keinen Status mitteilen und man nicht genau weiß ob der Befehl angekommen ist oder nicht. Wenn der Receiver aus ist, gibt es auch aktuell keine Möglichkeit Ihn mit dem Plugin anzuschalten, da die Netzwerkschnittstelle getrennt wird und der AVR nicht auf befehle reagiert.

**Comment by fighterzg6** [comment]
hallo, jetzt läuft es grad, keine Fehler bis auf das:

[2019-11-22 8:53:19] [AVR] Build Request Command: power-off undefined
(node:22409) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:22409) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase 

desweitern geht nur der Eingang STB , alles andere wird wild geschalten!?

**Comment by marcelkordek** [comment]
So, das plugin ist jetzt auch bei NPM verfügbar -> sudo npm install -g homebridge-harman-kardon-avr

**Comment by fighterzg6** [comment]
also erstmal fettes Dankeschön, läuft jetzt ganz gut!
auch Eingänge funktionieren!

ABER Jetzt läuft mein TV ja auch über die Homebridge und schaltet normalerweise den AVR aus und ein! wenn ich der Siri sage schalte Fernseher aus , schaltet sie auch den AVR aus! das will ich aber gar nicht! kann man das gerät als was anderes wie einen TV deklarieren???

**Comment by marcelkordek** [comment]
Kein Problem, gerne ;) 

Evtl. hängt es mit dem Namen zusammen. Sie erkennt den AVR als Fernseher und schaltet diesen dann mit aus. Man könnte evtl. per Konfiguration den "Aus" Befehl deaktivieren.

Wenn man den TV z.b. nur als "Schalter" deklariert kann man die Eingänge nicht mehr steuern.
