### ISSUE TITLE
I'm getting this error at startup.

### ISSUE THREAD

**Issue by ghost** [marcelkordek/homebridge-harman-kardon-avr#3]
The plugin "homebridge-harman-kardon-avr" requires a Homebridge version of ^0.4.49 which does not satisfy the current Homebridge version of 1.1.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

I love the plugin! It works great but it randomly causes homebridge to fail. I suspect this has something to do with it.

**Comment by willio** [comment]
~~I simply appended version 1.1.0 onto the package.json file.~~

~~`sudo nano /usr/local/lib/node_modules/homebridge-harman-kardon-avr/package.json`~~

~~on line 6, change `"^0.4.49"` to `"^1.1.0"`, which seems to have done the trick.~~

Didn't work after restart. Needs an update.

**Comment by marcelkordek** [comment]
Hi, 
should be fixed with v2.2.2.

Could you please send me the Log when Homebridge crashes?
