### ISSUE TITLE
not an issue, but a question

### ISSUE THREAD

**Issue by Itsmmai** [marcelkordek/homebridge-harman-kardon-avr#4]
Hi, Is this plugin only available for a avr or can I also user the HK One(s) with airplay ?

Kind regards,
Abel

**Comment by marcelkordek** [comment]
Hi Abel,

this Plugin is only tested with HK AVRs. Unfortunately I can not tell you whether it works with others. Can you send me a link of your receiver?

Greatings,
Marcel

**Comment by Itsmmai** [comment]
I'm so sorry, I totale missed your question. What do you want me to send?

Regards,
Ab
